CREATE DATABASE mydoctorpal2;
USE mydoctorpal;
CREATE TABLE Usuarios (
ID INT AUTO_INCREMENT PRIMARY KEY,
CPF CHAR(11) NOT NULL,
Nome VARCHAR(100) NOT NULL,
Email VARCHAR(100) NOT NULL UNIQUE,
Senha VARCHAR(30) NOT NULL,
Telefone CHAR(11) NOT NULL
);

CREATE TABLE Pacientes (
ID_Paciente INT AUTO_INCREMENT PRIMARY KEY,
ID INT NOT NULL,
Nascimento DATE NOT NULL,
FOREIGN KEY (ID) REFERENCES Usuarios (ID) ON DELETE CASCADE
);

CREATE TABLE Medicos (
ID_Medico INT AUTO_INCREMENT PRIMARY KEY,
ID INT NOT NULL,
CRM CHAR(6) NOT NULL UNIQUE,
Especialidade VARCHAR(100) NOT NULL,
FOREIGN KEY (ID) REFERENCES Usuarios (ID) ON DELETE CASCADE
);

CREATE TABLE Consultas (
ID_Consulta INT AUTO_INCREMENT PRIMARY KEY,
ID_Medico INT NOT NULL,
ID_Paciente INT NOT NULL,
Data_ DATE NOT NULL,
Horario TIME NOT NULL,
Descricao VARCHAR(200),
Status_ ENUM('CONFIRMADA', 'NEGADA') DEFAULT 'CONFIRMADA',
FOREIGN KEY (ID_Medico) REFERENCES Medicos (ID_Medico) ON DELETE CASCADE,
FOREIGN KEY (ID_Paciente) REFERENCES Pacientes (ID_Paciente) ON DELETE CASCADE
);

CREATE TABLE Formularios (
ID_Formulario INT AUTO_INCREMENT PRIMARY KEY,
ID_Paciente INT NOT NULL,
Altura INT NOT NULL,
Peso INT NOT NULL,
Sexo ENUM('Masculino', 'Feminino') NOT NULL,
Cirurgia BOOLEAN,
Cirurgia_Resposta VARCHAR(100),
Med_Continuo BOOLEAN,
Med_Continuo_Resposta VARCHAR(100),
Med_Controlado BOOLEAN,
Med_Controlado_Resposta VARCHAR(100),
FOREIGN KEY (ID_Paciente) REFERENCES Pacientes (ID_Paciente) ON DELETE CASCADE
);
CREATE TABLE Anotacao (
ID_Anotacao INT AUTO_INCREMENT PRIMARY KEY,
ID_Consulta INT NOT NULL,
Conteudo VARCHAR(200),
FOREIGN KEY (ID_Consulta) REFERENCES Consultas (ID_Consulta) ON DELETE CASCADE
);